services:
  atlasmd-docs:
    image: atlasmd:latest
    build:
      context: ../atlasmd-renderer
      dockerfile: Dockerfile
      args:
        APP_VERSION: dev
    restart: on-failure
    ports:
      - 47145:47145
      - 47146:4000
    environment:
      - APP_VERSION=dev
      - PORT=47145
    volumes:
      - ./content:/app/content
      - ./public:/app/public
      - ./config.toml:/app/config.toml
    develop:
      watch:
        - action: sync
          path: ./content
          target: /app/content
        - action: sync
          path: ./public
          target: /app/public
        - action: sync+restart
          path: ./config.toml
          target: /app/config.toml
