services:
  atlasmd:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_VERSION: dev
    image: atlasmd:latest
    ports:
      - 3003:3003
      - 4000:4000
    environment:
      - APP_VERSION=dev
      - PORT=3003
      - ATLAS_TITLE=Atlas
    volumes:
      - ./content:/app/content
      - ./public:/app/public
    develop:
      watch:
        - action: sync
          path: ./content
          target: /app/content
        - action: sync
          path: ./public
          target: /app/public
        - action: sync+restart
          path: ./nuxt.config.ts
          target: /app/nuxt.config.ts
        - action: sync+restart
          path: ./app.config.ts
          target: /app/app.config.ts
        - action: rebuild
          path: ./tokens.config.ts
        - action: rebuild
          path: ./yarn.lock
